### PR TITLE
[Feature] add auto merge background task

### PR DESCRIPTION
**Pull request by LindaSummer**
# Issue
#297 

We need to add an auto merge background task with cron expression scheduler.

# Proposed Changes
- add cron task for auto merge with [cron library](https://github.com/robfig/cron).
- add related unit tests

### CODE REVIEW

**Comment by LindaSummer** [comment]
Hi @roseduan, please take a look. Thanks. 😊

I have one problem when writing unit test for auto merge.

I don't know how to check whether merge action has been operated without an internal flag.

I think I should add such a unit test for case coverage.

Best Regards

**Comment by roseduan** [comment]
> Hi @roseduan, please take a look. Thanks. 😊
> 
> I have one problem when writing unit test for auto merge.
> 
> I don't know how to check whether merge action has been operated without an internal flag.
> 
> I think I should add such a unit test for case coverage.
> 
> Best Regards

Thanks for your PR.
What does 'internal flag' mean?

Merge operation will discard all invalid data, and rewrite all valid data into new data files.
So maybe you can check the valid keys, for example, you put 10 keys, and delete 5 keys, after merge, all keys num will be 5.

**Comment by LindaSummer** [comment]
> > Hi @roseduan, please take a look. Thanks. 😊
> > I have one problem when writing unit test for auto merge.
> > I don't know how to check whether merge action has been operated without an internal flag.
> > I think I should add such a unit test for case coverage.
> > Best Regards
> 
> Thanks for your PR. What does 'internal flag' mean?
> 
> Merge operation will discard all invalid data, and rewrite all valid data into new data files. So maybe you can check the valid keys, for example, you put 10 keys, and delete 5 keys, after merge, all keys num will be 5.

Hi @roseduan , thanks very much for your warm suggestion.

I'm sorry for lack of explanation for 'internal flag'.

Previously I wanted to add a flag for merge actions and write unit test with it. But it makes no sense for production code.

I'll use keys' total count for unit test.

Happy New Year! 🎉

Best Regards

**Comment by LindaSummer** [comment]
> > Hi @roseduan, please take a look. Thanks. 😊
> > I have one problem when writing unit test for auto merge.
> > I don't know how to check whether merge action has been operated without an internal flag.
> > I think I should add such a unit test for case coverage.
> > Best Regards
> 
> Thanks for your PR. What does 'internal flag' mean?
> 
> Merge operation will discard all invalid data, and rewrite all valid data into new data files. So maybe you can check the valid keys, for example, you put 10 keys, and delete 5 keys, after merge, all keys num will be 5.

Hi @roseduan , please take a look.

I have use datafile's key total count to make unit test. 

It works now! Thanks very much for your suggestion.

**Comment by roseduan** [comment]
Thanks, the CI job timeout is 10 minutes, please fix the unit tests.

**Comment by LindaSummer** [comment]
> Thanks, the CI job timeout is 10 minutes, please fix the unit tests.
> 
> There are some other failures

Hi @roseduan , sorry for forgot adding cleanup code for my unit tests.

I have ran this commit in my own repo's GitHub Actions.

Please take a look.

Thanks very much,
Best Regards

**Comment by roseduan** [comment]
Thanks for your great work, looking forward to your next PR!

**Comment by LindaSummer** [comment]
> Thanks for your great work, looking forward to your next PR!

Thanks for your warm help.

I'm satisfied to make some contribution. 😊

Best Regards

**Pull request merged**
